#INCLUDEFILE option("helix")
[[language]]
name = "rust"

#IF option("xtensa")
[language-server.rust-analyzer]
environment.RUSTUP_TOOLCHAIN = "stable"

#ENDIF
[language-server.rust-analyzer.config]
cargo.allTargets = false
#REPLACE riscv32imac-unknown-none-elf rust_target
cargo.target = "riscv32imac-unknown-none-elf"
#IF option("xtensa")
#REPLACE esp toolchain-name
check.extraEnv.RUSTUP_TOOLCHAIN = "esp"
#REPLACE esp toolchain-name
cargo.extraEnv.RUSTUP_TOOLCHAIN = "esp"
#ENDIF
